spring:
  mail:
    from: no-reply@reform.hmcts.net
    to:  Praveen.Saxena@HMCTS.NET
    subject:  Exception received at Rout
    host: mta.reform.hmcts.net
    port: 25
    enabled: false
    properties:
      mail-smtp:
        starttls:
          enable: false
        ssl:
          trust: "*"
azure:
  storage:
    account-name: rdpreview
    account-key: 61Sb95N8fFF5PNn/Gn5FjJFUg6wKJ/j6IWa0URdnAWnmjtluRPpJDk8uA3Zrx+u9gzUA8nF56rVJm1jl5dgTnQ==
    container-name: ${CONTAINER_NAME:jud-ref-data}
    https-enabled-url: ${HTTPS_ENABLED_URL:false}
    blob-url: ${BLOB_URL:http://rdpreview.blob.core.windows.net}
    blob-https-url: ${BLOB_HTTPS_URL:http://rdpreview.blob.core.windows.net}





