spring:
  mail:
    to: abhijit.diwan@hmcts.net,sourav.roy@hmcts.net
    subject:  ${component.name:data-ingestion} - Exception in processing -
    host: mta.reform.hmcts.net
    port: 25
    enabled:  ${mail.enabled:false}
    properties:
      mail-smtp:
        starttls:
          enable: false
        ssl:
          trust: "*"


azure:
  storage:
    account-name: ${ACCOUNT_NAME:ACCOUNT_NAME}
    account-key: ${ACCOUNT_KEY:ACCOUNT_KEY}
    container-name: ${CONTAINER_NAME:CONTAINER_NAME}
    blob-url-suffix: ${BLOB_URL_SUFFIX:BLOB_URL_SUFFIX}

idempotent-flag-ingestion: ${idempotent-flag:true}
