spring:
  mail:
    from: no-reply@reform.hmcts.net
    to:  Praveen.Saxena@HMCTS.NET
    subject:  Exception received at Rout
    host: mta.reform.hmcts.net
    port: 25
    enabled: false
    properties:
      mail-smtp:
        starttls:
          enable: false
        ssl:
          trust: "*"
azure:
  storage:
    account-name: ${ACCOUNT_NAME:ACCOUNT_NAME}
    account-key: ${ACCOUNT_KEY:ACCOUNT_KEY}
    container-name: ${CONTAINER_NAME:CONTAINER_NAME}
    blob-url-suffix: ${BLOB_URL_SUFFIX:BLOB_URL_SUFFIX}





